name: CI Pipeline (Monorepo)
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

permissions:
  contents: read
  pull-requests: read

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install backend dependencies
        working-directory: ./backend
        run: bun install --frozen-lockfile

      - name: Type check backend
        working-directory: ./backend
        run: bun run type-check

      - name: Lint backend
        working-directory: ./backend
        run: bun run lint:check

      - name: Format check backend
        working-directory: ./backend
        run: bun run format:check

      - name: Test backend
        working-directory: ./backend
        run: bun test

      - name: Build backend
        working-directory: ./backend
        run: bun run build

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Type check frontend
        working-directory: ./frontend
        run: bun run type-check

      - name: Lint frontend
        working-directory: ./frontend
        run: bun run lint:check

      - name: Format check frontend
        working-directory: ./frontend
        run: bun run format:check

      - name: Test frontend
        working-directory: ./frontend
        run: bun run test

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t wahub:test .
        
      - name: Test Docker build
        run: |
          echo "Docker build completed successfully"
          docker images wahub:test
