name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run format
      - run: bun run lint
      - run: bun run build
      - run: bun run test
